# Generated by Django 3.1.3 on 2020-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201127_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lastBid',
            field=models.IntegerField(default=0),
        ),
    ]
